# Generated by Django 3.0.4 on 2020-05-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
    ]
