# Generated by Django 3.0.4 on 2020-05-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200513_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='quantity',
        ),
    ]
